name: Daily Property Update Emails

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  send-daily-emails:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Prisma client
        run: npx prisma generate
        
      - name: Send daily emails
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          AMPRE_TOKEN: ${{ secrets.AMPRE_TOKEN }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: node scripts/send-daily-emails.js
          
      - name: Report results
        if: always()
        run: |
          echo "Daily email job completed at $(date)"
          echo "Check the logs above for results"
